# Set the zsh root directoy
export ZSH_ROOT=$HOME/.zsh

# Set some environmet variables
source "$ZSH_ROOT/functions/environment.zsh"

# anyenv
source "$ZSH_ROOT/functions/anyenv.zsh"

# zplug
source "$ZSH_ROOT/functions/zplug.zsh"

# Add fpath for completions
# There are completion functions named like '_function'.
fpath=($ZSH_ROOT/completions $fpath)

# homebrew
# gcloud-cli
source '/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
source '/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'

# aws-cli
source $HOME/.anyenv/envs/pyenv/versions/general-env/bin/aws_zsh_completer.sh

source "$ZSH_ROOT/functions/completion.zsh"

autoload -Uz compinit
compinit -D

# Load custom plugins
while read myfunction; do
  source "$ZSH_ROOT/functions/${myfunction}.zsh"
done < <(cat << EOF
alias
history
colorize
git
bindkey
termsupport
prompt
autojump
direnv
EOF
)

# credentials
if [ -f $ZSH_ROOT/credentials ];then
  source $ZSH_ROOT/credentials
fi

# tabtab source for slss package
# uninstall by removing these lines or running `tabtab uninstall slss`
[[ -f /Users/fyoshino/.anyenv/envs/ndenv/versions/v10.16.3/lib/node_modules/serverless/node_modules/tabtab/.completions/slss.zsh ]] && . /Users/fyoshino/.anyenv/envs/ndenv/versions/v10.16.3/lib/node_modules/serverless/node_modules/tabtab/.completions/slss.zsh
export JAVA_TOOLS_OPTIONS="-Dlog4j2.formatMsgNoLookups=true"
